import "dotenv/config";
import { buildAuditPipeline } from "./graph/pipeline";
import { AuditReportSchema } from "./graph/state";
import { writeFile, mkdir } from "fs/promises";
import path from "path";

async function main() {
  const contractPath = process.argv[2];

  if (!contractPath) {
    console.error("❌ Usage: bun run src/main.ts <path-to-contract.sol>");
    process.exit(1);
  }

  console.log("\n🚀 DynaAudit — Smart Contract Audit Starting\n");
  console.log("═".repeat(50));

  const pipeline = buildAuditPipeline();

  const threadId = `audit-${Date.now()}`;

  const finalState = await pipeline.invoke(
    {
      contractPath,
      contractCode: "", // populated by readContractNode
      contractSummary: "",
      currentPhase: 1,
    },
    {
      configurable: { thread_id: threadId },
    },
  );

  console.log("\n" + "═".repeat(50));
  console.log("📊 Audit Complete\n");

  if (!finalState.finalReport) {
    console.error("❌ Audit failed — no final report generated");
    process.exit(1);
  }

  const report = AuditReportSchema.parse(finalState.finalReport);

  // ── Print summary to console ──────────────────────────────────────────────

  console.log(`Contract  : ${report.contractName}`);
  console.log(`Risk Score: ${report.riskScore}`);
  console.log(`Findings  : ${report.totalFindings}`);
  console.log(`Audited At: ${report.auditedAt}`);
  console.log(`\nSummary:\n${report.summary}\n`);

  console.log("Findings:");
  report.findings.forEach((f, i) => {
    console.log(
      `  [${i + 1}] ${f.severity.padEnd(8)} | ${f.confidence.toFixed(2)} confidence | ${f.title}${f.isNovel ? " ⚠️  NOVEL" : ""}`,
    );
  });

  // ── Write reports to disk ─────────────────────────────────────────────────

  const reportsDir = path.resolve("reports");
  await mkdir(reportsDir, { recursive: true });

  const timestamp = new Date().toISOString().replace(/[:.]/g, "-");
  const baseName = path.basename(contractPath, ".sol");

  // JSON report
  const jsonPath = path.join(reportsDir, `${baseName}-${timestamp}.json`);
  await writeFile(jsonPath, JSON.stringify(report, null, 2), "utf-8");

  // Markdown report
  const mdPath = path.join(reportsDir, `${baseName}-${timestamp}.md`);
  await writeFile(mdPath, buildMarkdownReport(report, contractPath), "utf-8");

  console.log(`\n📁 Reports saved:`);
  console.log(`   JSON : ${jsonPath}`);
  console.log(`   MD   : ${mdPath}`);
}

// ─── Markdown Report Builder ──────────────────────────────────────────────────

function buildMarkdownReport(
  report: ReturnType<typeof AuditReportSchema.parse>,
  contractPath: string,
): string {
  const severityEmoji: Record<string, string> = {
    CRITICAL: "🔴",
    HIGH: "🟠",
    MEDIUM: "🟡",
    LOW: "🟢",
    SAFE: "✅",
  };

  return `# DynaAudit Report — ${report.contractName}

**Audited At:** ${report.auditedAt}
**Contract:** \`${contractPath}\`
**Risk Score:** ${severityEmoji[report.riskScore]} ${report.riskScore}
**Total Findings:** ${report.totalFindings}

---

## Executive Summary

${report.summary}

---

## Findings

${report.findings
  .map(
    (f, i) => `
### [${i + 1}] ${severityEmoji[f.severity]} ${f.title}

| Field | Value |
|---|---|
| Severity | ${f.severity} |
| Confidence | ${(f.confidence * 100).toFixed(0)}% |
| Novel Exploit | ${f.isNovel ? "⚠️ Yes — matches post-training exploit pattern" : "No"} |
${f.affectedLines ? `| Affected Lines | ${f.affectedLines.join(", ")} |` : ""}
${f.matchedExploit ? `| Matched Exploit | ${f.matchedExploit} |` : ""}

${f.description}
`,
  )
  .join("\n---\n")}

---

*Generated by DynaAudit — Exploit-Driven Dynamic RAG for Smart Contract Vulnerability Detection*
`;
}

main().catch((err) => {
  console.error("❌ Fatal error:", err);
  process.exit(1);
});
